[core]
name:虚空空气
displayDescription:更新测试中
maxHp:0
mass:0
price:0
radius:0
disableDeathOnZeroHp:true
disableAllUnitCollisions:true
hideScorchMark:true
numBitsOnDeath:0
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
#禁止直接攻击:真
isUnselectable:true
stayNeutral:true
#创建时中立:真
createOnAggressiveTeam:true
#此模板在"基础模板"上修改

ignoreInUnitCapCalculation:true

[graphics]
#图像节需要设置主体图像
image:air.png
scaleImagesTo:20
disableLowHpFire:true
disableLowHpSmoke:true
image_wreak:NONE
[attack]
canAttack:true
maxAttackRange:1
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackNotTouchingWaterUnits:true
canAttackUnderwaterUnits:true
isMelee:true
[turret_1]

invisible:true
x:0
y:0
[projectile_2]
directDamage:100
life:5
[movement]
movementType:NONE