[core]
name:空气
maxHp:1
mass:0
price:0
radius:0
disableAllUnitCollisions:true
hideScorchMark:true
numBitsOnDeath:0
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
canNotBeDirectlyAttacked:true
canReclaimResources:true
resourceRate:99999
reclaimPrice:0
stayNeutral:true
createNeutral:true
#此模板在"基础模板"上修改
#是建筑:真
[graphics]
#图像节需要设置主体图像
image:air.png
scaleImagesTo:20
disableLowHpFire:true
disableLowHpSmoke:true
image_wreak:NONE
[attack]
canAttack:false
[movement]
movementType:NONE