[core]
stayNeutral:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
name:基岩
maxHp:99999999
mass:999999
price:0
radius:0
#禁止选择:真
#不可选择为目标:真
disableDeathOnZeroHp:true
#此模板在"基础模板"上修改
isBuilding:true
createNeutral:true
buildSpeed:0.01

#此代码规定建筑范围
footprint:0,0,0,0
constructionFootprint:0,0,0,0

[graphics]
#图像节需要设置主体图像
image:Bedrock.png
scaleImagesTo:20
[attack]
canAttack:false
[movement]
movementType:BUILDING