[core]
autoTriggerCooldownTime:5
defineUnitMemory:number 蔓延代数
updateUnitMemoryRate:10
updateUnitMemory:蔓延代数=1
autoTriggerCheckRate:every8Frames
name:岩浆
maxHp:0
mass:0
price:0
radius:0
#是建筑:真

disableAllUnitCollisions:true
stayNeutral:true
createNeutral:true
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
isUnselectable:true
disableDeathOnZeroHp:true
ignoreInUnitCapCalculation:true
autoTriggerCooldownTime:5
[graphics]
image:magma.png
scaleImagesTo:20
icon_zoomed_out_neverShow:true
[attack]
canAttack:false

[movement]
movementType:NONE
[hiddenAction_流体蔓延]
resetCustomTimer:if self.customTimer(laterThanSeconds=5)
autoTrigger:if self.customTimer(laterThanSeconds=5)
#重置自定义计时器:如果 自身自定义计时器(laterThanSeconds=50)
autoTriggerOnEventRecursionLimit:10
spawnUnits:岩浆(offsetX=20, skipIfOverlapping=true), 岩浆(offsetX=-20, skipIfOverlapping=true), 岩浆(offsetY=20, skipIfOverlapping=true)