[core]
autoTriggerCheckRate:every8Frames
name:岩浆
maxHp:0
mass:0
price:0
radius:0
#是建筑:真

disableAllUnitCollisions:true
stayNeutral:true
createNeutral:true
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
isUnselectable:true
disableDeathOnZeroHp:true
ignoreInUnitCapCalculation:true
[graphics]
image:magma.png
scaleImagesTo:20

[attack]
canAttack:false

[movement]
movementType:NONE

[hiddenAction_流体蔓延]
autoTrigger:if self.customTimer(laterThanSeconds=50)
autoTriggerOnEventRecursionLimit:50

spawnUnits:岩浆(offsetX=20, skipIfOverlapping=true), 岩浆(offsetX=-20, skipIfOverlapping=true), 岩浆(offsetY=20, skipIfOverlapping=true)