[core]
stayNeutral:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
name:石头
maxHp:50
mass:70
price:1
radius:5
#此模板在"基础模板"上修改
isBuilding:true
createNeutral:true
buildSpeed:0.01

#此代码规定建筑范围
footprint:0,0,0,0
constructionFootprint:0,0,0,0
#切换至中立队伍:真
reclaimPrice:10
resourceRate:1
techLevel:1

builtFrom_1_name:builder
builtFrom_1_pos:1
[graphics]
#图像节需要设置主体图像
image:Stone.png
scaleImagesTo:20
[attack]
canAttack:false
[movement]
movementType:BUILDING