[core]
autoTriggerCheckRate:every8Frames
name:水
maxHp:0
mass:0
price:0
radius:0
#是建筑:真

disableAllUnitCollisions:true
stayNeutral:true
createNeutral:true
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
isUnselectable:true
disableDeathOnZeroHp:true
ignoreInUnitCapCalculation:true
[graphics]
image:Water.png
scaleImagesTo:20

[attack]
canAttack:false

[movement]
movementType:NONE

[hiddenAction_流体蔓延]
autoTrigger:if self.customTimer(laterThanSeconds=50)
autoTriggerOnEventRecursionLimit:50
spawnUnits:水(offsetX=20, skipIfOverlapping=true), 水(offsetX=-20, skipIfOverlapping=true), 水(offsetY=20, skipIfOverlapping=true)